### ISSUE TITLE
Release >= 0.6.3 breaks server side rendering

### ISSUE THREAD

**Issue by texttechne** [JedWatson/react-input-autosize#26]
Error:
```
ReferenceError: window is not defined
    at ...\node_modules\react-select\node_modules\react-input-autosize\lib\AutosizeInput.js:10:6
    at Object.<anonymous> (...\node_modules\react-select\node_modules\react-input-autosize\lib\AutosizeInput.js:16:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (...\node_modules\react-sel
ect\lib\Select.js:11:13)
    at Module._compile (module.js:456:26)
```

Problem appeared in `react-select` after having it reinstalled recently. It's dependency to react-input-autosize is specified as `^0.6.2` or `^0.6.0`. This is quite unfortunate, since there's no easy way to fix `react-select` by downgrading a minor version: Every version is broken in this respect now...

**Comment by Webkadabra** [comment]
Yes, +1 that one, a major issue!

**Comment by JedWatson** [comment]
Sorry about that - fixed in 0.6.5

**Comment by Webkadabra** [comment]
Thanks!

**Comment by texttechne** [comment]
Great response time. Thanks a lot!
